#-------------------------------
# General Site Settings

menu:
#- {name: 'About', url: ''}
- {name: 'Research', url: 'publications.html'}
- {name: 'Software', url: 'software.html'}
#- {name: 'Projects', url: 'projects.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Carlos Mastalli is a robotics researcher focused on multi-contact planning and control for legged robots. He is main motivation is to enable robots (e.g. HyQ, HRP-2, Talos, Atlas) to move everywhere by combining optimal control and machine learning.'
  rel-author: 'Carlos Mastalli'
  rel-publisher: 'Carlos Mastalli'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-113566398-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# About Section

about: >
  ## About Me - [CV](/personal/cmastalli_cv.pdf)

  <img src="/assets/img/carlos_mastalli.jpeg" alt="Drawing" style="width: 26.6%;"/>
  <img src="/assets/img/publications/avoiding_slippage.gif" align="right" alt="Drawing" style="width: 47.6%;"/>

  <p class="lead" style="font-variant:small-caps">
      Optimal Control - Motion Planning - Trajectory Optimization<br />
      Reinforcement Learning - Legged Robots - Perception
  </p>

  I am a robotics researcher working on the interception of model predictive control and machine learning for motor control in legged robots. The aim of my research is to enable robots to move everywhere. In particular, I am focused on the problem of loco-manipulation tasks since it combines the main challenges in robot mobility: high-dimensional and unactuated systems, discontinuous dynamics, robot interaction and perception. For that, I focus on methods that combine optimal control and machine learning, allowing us to explore the knowledge of the system but also the vast robot's data.
  
    
  I completed my PhD on "[Planning and Execution of Dynamic Whole-Body Locomotion on Challenging Terrain](/publications/thesis.html)" in April 2017 in the [Dynamic Legged System lab](https://dls.iit.it/) at Istituto Italiano di Tecnologia. After that, I served as Research Fellow from April to December 2017. During this period, I mainly contributed to planning, perception and control framework for legged locomotion on challenging terrain. I also designed a considerably part of the HyQ's software framework. In my career I have spent fruitful time in different Europen research institutions: IIT (Genova), ETH Zurich, LAAS-CNRS and The University of Edinburgh.


#-------------------------------
# Research Section

research: >
  ## Research


#-------------------------------
# Work Section

projects:
- {name: 'Hierarchical Planning of Dynamic Movements without Scheduled Contact Sequences', folder: 'hierarchical', file: 'projects/hierarchical.html'}
- {name: 'Planning and Execution of Dynamic Whole-Body Locomotion for a Hydraulic Quadruped on Challenging Terrain', folder: 'decoupled', file: 'projects/decoupled.html'}


#-------------------------------
# Software Section

software: >
  ## Software


#-------------------------------
# Contact Section

contact: >
  ## Contact
  
  If you'd like to know more about my research or would just like to discuss past or future projects, feel free to contact me [by email](mailto:carlos.mastalli@gmail.com) or through [LinkedIn](https://www.linkedin.com/in/carlos-mastalli-27314118/).


social:
- {icon: 'github', link: 'https://github.com/cmastalli'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/carlos-mastalli-27314118/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCgC0AFO3J0454k3w0j5o3Vg?view_as=subscriber'}
- {icon: 'envelope', link: 'mailto:carlos.mastalli@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
