#-------------------------------
# General Site Settings

menu:
- {name: 'About', url: 'pages/about.html'}
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112847486-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# About Section

about: >
  # About
  
  
  Hi, thanks for taking the time to stop by.  My name is Dylan and I recently graduated from the University of Hawaii at Manoa with a BS in Computer Engineering.  I am currently seeking a full-time role as a Data Analyst/Scientist. My interests include machine learning, data analysis and visualization, and anything Python.  
  
  On this site you'll find various projects I have worked on either on the side or as part of coursework in college. I also have a blog where I'll write about various topics from machine learning to web development.  I will also use it to track my progress through various MOOCs or other online courses.

contact: >
  # Contact
  
  You may contact me [by email](mailto:dylannakahodo@gmail.com) or through [LinkedIn](https://www.linkedin.com/in/dylan-nakahodo/).

#-------------------------------
# Work Section

projects:
- {name: 'Adventure Portal', folder: 'adventure-portal', file: 'projects/adventure-portal.html'}


#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/dylannakahodo'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/dylan-nakahodo/'}
- {icon: 'envelope', link: 'mailto:dylannakahodo@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
