#-------------------------------
# General Site Settings

menu:
#- {name: 'About', url: ''}
- {name: 'Publications', url: 'publications.html'}
- {name: 'Software', url: 'software.html'}
#- {name: 'Projects', url: 'projects.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Carlos Mastalli is a robotics researcher focused on multi-contact planning and control for legged robots. He is main motivation is to enable robots (e.g. HyQ, HRP-2, Talos, Atlas) to move everywhere by combining optimal control and machine learning.'
  rel-author: 'Carlos Mastalli'
  rel-publisher: 'Carlos Mastalli'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-113566398-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# About Section

about: >
  ## About Me - [CV](/personal/cmastalli_cv.pdf)

  <img src="/assets/img/carlos_mastalli.jpeg" alt="Drawing" style="width: 26.6%;"/>
  <img src="/assets/img/publications/avoiding_slippage.gif" align="right" alt="Drawing" style="width: 47.6%;"/>

  <p class="lead" style="font-variant:small-caps">
      Optimal Control - Motion Planning - Trajectory Optimization<br />
      Reinforcement Learning - Machine Learning - Legged Robots
  </p>

  I am a robotics researcher working in the interception of model predictive control and machine learning for motor control in legged robots. The aim of my research is to enable robots to move everywhere. In particular, I am focused on the problem of loco-manipulation tasks since it combines the main challenges in robot mobility. My research combines the formalism of model-base approach with the exploration of vast robot's data.
  
    
  I completed my PhD on "[Planning and Execution of Dynamic Whole-Body Locomotion on Challenging Terrain](/publications/thesis.html)" in April 2017 in the [Dynamic Legged System lab](https://dls.iit.it/) at Istituto Italiano di Tecnologia. After that, I served as Research Fellow from April to December 2017. During this period, I mainly contributed to planning, perception and control framework for legged locomotion on challenging terrain. I also designed a considerably part of the HyQ's software framework. In my career, I have spent fruitful time in different European research institutions: IIT (Genova), ETH Zurich, LAAS-CNRS, The University of Edinburgh and Tha Alan Turing Institute.

  #### Selected Publications

    <table>
    <colgroup>
      <col width="20%" />
      <col width="80%" />
    </colgroup>
    <tbody>
    <td markdown="span"> [<img src="/assets/img/publications/avoiding_slippage-compressed.gif" align="right" alt="Drawing" style="height: 100px; margin:0px 10px"/>](https://www.youtube.com/watch?v=KI9x1GZWRwE)</td>
    <td markdown="span">[Motion Planning for Quadrupedal Locomotion: Coupled Planning, Terrain Mapping and Whole-Body Control](/publications/locomotion20tro.html).
    **C. Mastalli**, M. Focchi, I. Havoutis, D. G. Caldwell and C. Semini
    <br> *IEEE Transactions on Robotics (T-RO), 2020*</td>

    <tr height ="10px"></tr>

    <td markdown="span"> [<img src="/assets/img/publications/talos_jumps-compressed.gif" align="right" alt="Drawing" style="height: 100px; margin:0px 10px"/>](https://youtu.be/rZ135Dw92No)</td>
    <td markdown="span">[Crocoddyl: An Efficient and Versatile Framework for Multi-Contact Optimal Control](/publications/crocoddyl20icra.html).
    **C. Mastalli**, R. Budhiraja, W. Merkt, G. Saurel, B. Hammoud, M. Naveau, J. Carpentier, L. Righetti, S. Vijayakumar and N. Mansard
    <br> *IEEE International Conference on Robotics and Automation (ICRA), 2020*</td>
    
    <tr height ="10px"></tr>
    
    <td markdown="span"> [<img src="/assets/img/publications/coupled_plan-compressed.gif" align="right" alt="Drawing" style="height: 100px; margin:0px 10px"/>](https://www.youtube.com/watch?v=79bb2KTULrw)</td>
    <td markdown="span">[Trajectory and Foothold Optimization using Low-Dimensional Models for Rough Terrain Locomotion](/publications/coupled17icra.html).
    **C. Mastalli**, M. Focchi, I. Havoutis, A. Radulescu, S. Calinon, J. Buchli, D. G. Caldwell and C. Semini
    <br> *IEEE International Conference on Robotics and Automation (ICRA), 2017*</td>
    
    <tr height ="10px"></tr>
    
    <td markdown="span"> [<img src="/assets/img/publications/torque_limits-compressed.gif" align="right" alt="Drawing" style="height: 100px; margin:0px 10px"/>](https://www.youtube.com/watch?v=RXIAQJx5938&t=2s)</td>
    <td markdown="span">[Simultaneous Contact, Gait and Motion Planning for Robust Multi-Legged Locomotion via Mixed-Integer Convex Optimization](/publications/gait17ral.html).
    B. Aceituno, **C. Mastalli**, H. Dai, M. Focchi, A. Radulescu, D. G. Caldwell, J. Cappelletto, J. C. Grieco, G. Fernandez and C. Semini
    <br> *IEEE Robotics and Automation Letters (RA-L), 2017*</td>

    <tr height ="10px"></tr>

    <td markdown="span"> [<img src="/assets/img/publications/fwp_walk-compressed.gif" align="right" alt="Drawing" style="height: 100px; margin:0px 10px"/>](https://www.youtube.com/watch?v=X36PLdTNr6U)</td>
    <td markdown="span">[Application of Wrench based Feasibility Analysis to the Online Trajectory Optimization of Legged Robots](/publications/feasibility18ral.html).
    R. Orsolino, M. Focchi, **C. Mastalli**, H. Dai, D. G. Caldwell and C. Semini
    <br> *IEEE Robotics and Automation Letters (RA-L), 2018*</td>
    </tbody>
    </table>

#-------------------------------
# Research Section

research: >
  ## Research


#-------------------------------
# Work Section

projects:
- {name: 'Hierarchical Planning of Dynamic Movements without Scheduled Contact Sequences', folder: 'hierarchical', file: 'projects/hierarchical.html'}
- {name: 'Planning and Execution of Dynamic Whole-Body Locomotion for a Hydraulic Quadruped on Challenging Terrain', folder: 'decoupled', file: 'projects/decoupled.html'}


#-------------------------------
# Software Section

software: >
  ## Software


#-------------------------------
# Contact Section

contact: >
  ## Contact
  
  If you'd like to know more about my research or would just like to discuss past or future projects, feel free to contact me [by email](mailto:carlos.mastalli@gmail.com) or through [LinkedIn](https://www.linkedin.com/in/carlos-mastalli-27314118/).


social:
- {icon: 'github', link: 'https://github.com/cmastalli'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/carlos-mastalli-27314118/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCgC0AFO3J0454k3w0j5o3Vg?view_as=subscriber'}
- {icon: 'envelope', link: 'mailto:carlos.mastalli@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
